name = "impulse-api"
main = "src/worker.js"
compatibility_date = "2025-08-01"

[[d1_databases]]
binding = "DB"
database_name = "impulse_wallet"
database_id = ""

# When deploying via GitHub actions or CLI, set database_id above to the
# identifier returned by `wrangler d1 create impulse_wallet`. The binding
# name "DB" is referenced in worker.js when connecting to the database.
